name: Trigger auto deployment for edoardo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/edoardo-AutoDeployTrigger-e2336967-d6b5-43f5-a8b5-567402b5c5dc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EDOARDO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EDOARDO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EDOARDO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: gtxcontainerregistry.azurecr.io
          registryUsername: ${{ secrets.EDOARDO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EDOARDO_REGISTRY_PASSWORD }}
          containerAppName: edoardo
          resourceGroup: edoardo
          imageToBuild: gtxcontainerregistry.azurecr.io/edoardo:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


